#define EMPTY_TARGET_NAME_ERROR 1
#define OPEN_FILE_ERROR 2
#define GET_FILE_POSITION_ERROR 3
#define GET_FILE_SIZE_ERROR 4
#define MEMORY_ALLOCATION_ERROR 5
#define DESTROY_FILE_ERROR 6
#define SET_ACCESS_ERROR 7
#define COMMAND_LINE_ARGUMENTS_ERROR 8