#define OPEN_FILE_ERROR 1
#define GET_FILE_POSITION_ERROR 2
#define GET_FILE_SIZE_ERROR 3
#define MEMORY_ALLOCATION_ERROR 4
#define DESTROY_FILE_ERROR 5
#define SET_ACCESS_ERROR 6
#define COMMAND_LINE_ARGUMENTS_ERROR 7